In [2]:
import numpy 

## Numpy Arrays
You are given a space separated list of numbers.
Your task is to print a reversed NumPy array with the element type float .

### Input Format
A single line of input containing space separated numbers.

#### Output Format
Print the reverse NumPy array with type float.

### Sample Input
1 2 3 4 -8 -10

### Sample Output
[-10. -8. 4. 3. 2. 1.

In [3]:
def arrays(arr):
    arr=numpy.array(arr,float)
    return arr[-1::-1]

print('Input')
arr = input().strip().split(' ')
result = arrays(arr)
print('\nOutput')
print(result)

Input
1 2 3 4 -8 -10

Output
[-10.  -8.   4.   3.   2.   1.]


## Q.2 Shape and Reshape

You are given a space separated list of nine integers. Your task is to convert this list into a 3X3 NumPy
array.

### Input Format
A single line of input containing 9 space separated integers.

### Output Format
Print the 3X3 NumPy array.

### Sample Input
(a). Using shape to get array dimensions

(b). Using shape to change array dimensions

1 2 3 4 5 6 7 8 9
### Sample Output
    [[1 2 3]
     [4 5 6]
     [7 8 9]]

In [4]:
import numpy as np
print('Input')
arr=input().split()
arr=np.array(arr,int).reshape(3,3)
print('\nOutput')
print(arr)

Input
1 2 3 4 5 6 7 8 9

Output
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Q.3 Transpose and Flatten

You are given a N X M integer array matrix with space separated elements ( N = rows and M = columns).
Your task is to print the transpose and flatten results.

### Input Format
The first line contains the space separated values of N and M .
The next lines contains the space separated elements of M columns.

### Output Format
First, print the transpose array and then print the flatten.

### Sample Input
    2 2
    1 2
    3 4
### Sample Output
    [[1 3]
     [2 4]]
    [1 2 3 4]

In [6]:

N,M=map(int,input().split())
arr=np.array([input().split() for i in range (N)],int).reshape(N,M)
print(np.transpose(arr))
print(arr.flatten())


2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


## Q.4 Np.concatenate

You are given two integer arrays of size N X P and M X P (N & M are rows, and P is the column). Your
task is to concatenate the arrays along axis 0 .
### Input Format

The first line contains space separated integers N,M and P.

The next N lines contains the space separated elements of the P columns.

After that, the next  M lines contains the space separated elements of theP  columns.

### Output Format
Print the concatenated array of size(N+M) X P .

### Sample Input

    4 3 2
    1 2
    1 2
    1 2
    1 2
    3 4
    3 4
    3 4

### Sample Output
    [[1 2]
     [1 2]
     [1 2]
     [1 2]
     [3 4]
     [3 4]
     [3 4]] 



In [4]:
import numpy as np
N,M,P=map(int,input().split())
arr1=np.array([input().split()for i in range(N)],int)
arr2=np.array([input().split()for i in range(M)],int)

arr=np.concatenate((arr1,arr2),axis=0)
print('\nOutput\n')
print(arr)


4 3 2
1 2 
1 2 
1 2 
1 2
3 4
3 4
3 4

Output

[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


## Q.5 Numpy zeros and ones
You are given the shape of the array in the form of space-separated integers, each integer representing
the size of different dimensions, your task is to print an array of the given shape and integer type using
the tools numpy.zeros and numpy.ones .

### Input Format
A single line containing the space-separated integers.

### Output Format
First, print the array using the numpy.zeros tool and then print the array with the numpy.ones tool.

### Sample Input 0
3 3 3

#### Sample Output 0
    [[[0 0 0]
      [0 0 0]
      [0 0 0]]

     [[0 0 0]
      [0 0 0]
      [0 0 0]]

     [[0 0 0]
      [0 0 0]
      [0 0 0]]]
     
    [[[1 1 1]
      [1 1 1]
      [1 1 1]]

     [[1 1 1]
      [1 1 1]
      [1 1 1]]

     [[1 1 1]
      [1 1 1]
      [1 1 1]]]


In [5]:
import numpy as np
dim=tuple(map(int,input().split()))
arr1=np.zeros(dim,dtype=np.int)
arr2=np.ones(dim,dtype=np.int)
print(arr1)
print(arr2)


3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


## Q.6 Numpy Eyes and Identity 
Your task is to print an array of size N X M with its main diagonal elements as 0's and 1's everywhere else.

### Input Format
A single line containing the space separated values of N and M .
N denotes the rows.
M denotes the columns.

### Output Format
Print the desired N X M array.

### Sample Input
3 3

### Sample Output
  
    [[ 1.  0.  0.]
     [ 0.  1.  0.]
     [ 0.  0.  1.]]

In [1]:
import numpy as np
np.set_printoptions(legacy='1.13')

N,M=map(int,input().split())
 
arr=np.eye(N,M)
print(arr)

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Q.7 Array Maths
You are given two arrays (A & B) of dimensions N X M .
Your task is to perform the following operations:
1. Add (A + B)
2. Subtract (A - B)
3. Multiply (A * B)
4. Divide (A / B)
5. Mod (A % B)
6. Power (A ** B)

### Input Format
The first line contains two space separated integers,N and M.

The next N lines contains M space separated integers of array A .

The following lines A contains M space separated integers of array B.

### Output Format
Print the result of each operation in the given order under Task.

### Sample Input
    1 4
    1 2 3 4
    5 6 7 8

### Sample Output

    [[ 6 8 10 12]]
    [[-4 -4 -4 -4]]
    [[ 5 12 21 32]]
    [[0 0 0 0]]
    [[1 2 3 4]]
    [[ 1 64 2187 65536]]

In [3]:
import numpy as np
print('Input')
N,M=map(int,input().split())

A=np.array([input().split() for i in range (N)],int)
B=np.array([input().split() for i in range (N)],int)

print('\nOutput\n')
print(A+B)
print(A-B)
print(A*B)
print(A//B)
print(A%B)
print(A**B)




Input
1 4
1 2 3 4
5 6 7 8

Output

[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


## Q.8 Floor, Ceil and Rint

You are given a 1-D array,A. Your task is to print the floor,ceil and rint of all the elements of A.

### Input Format
A single line of input containing the space separated elements of array A

### Output Format
On the first line, print floor of A.
On the second line, print the ceilof A.
On the third line, print the rint of A.

### Sample Input 
1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9

### Sample Output
    [ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
    [  2.   3.   4.   5.   6.   7.   8.   9.  10.]
    [  1.   2.   3.   4.   6.   7.   8.   9.  10.]

In [4]:
import numpy as np
np.set_printoptions(legacy='1.13')

print('input')
A=np.array(input().split(),float)

print('\nOutput')
print(np.floor(A))
print(np.ceil(A))
print(np.rint(A))



input
1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9

Output
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


## Q.9 Sum and Prod

You are given a 2-D array with dimensions N X M.Your task is to perform the sum tool over axis 0 and then find the product of that result.

### Input Format
The first line of input contains space separated values of N and M .

The next N lines contains M space separated integers.

### Output Format
Compute the sum along axis 0 . Then, print the product of that sum.

### Sample Input
    2 2
    1 2
    3 4

### Sample Output
    24


In [7]:
import numpy as np
print('input')
N,M=map(int,input().split())

A=np.array([input().split()for i in range(N)],int)

Sum=np.sum(A,axis=0)
print('\nOutut')
print(np.prod(Sum))


input
2 2 
1 2
3 4

Outut
24


## Q.10 Numpy Min and Max

You are given a 2-D array with dimensions N X M .
Your task is to perform the min function over axis 1 and then find the max of that.

### Input Format
The first line of input contains the space separated values of N and M .
The next N lines contains M space separated integers.

### Output Format
Compute the min along axis 1 and then print the max of that result.

### Sample Input
    4 2
    2 5
    3 7
    1 3
    4 0

### Sample Output
    3

In [8]:
import numpy as np
print('Input')
N,M=map(int,input().split())

A=np.array([input().split() for i in range (N)],int)

Min=np.min(A,axis=1)
print('\nOutput')
print(np.max(Min))

Input
4 2 
2 5 
3 7 
1 3 
4 0 

Output
3


## Q.11 Mean, Var, and Std

You are given a 2-D array of size N X M.
Your task is to find:
1. The mean along axis 1
2. The var along axis 0
3. The std along axis None

### Input Format
The first line contains the space separated values of N and M .
The next N lines contains M space separated integers.

### Output Format
First, print the mean.
Second, print the var.
Third, print the std.

### Sample Input
    2 2
    1 2
    3 4

### Sample Output
    [ 1.5 3.5]
    [ 1. 1.]
    1.11803398875

In [10]:
import numpy as np
print('Input')

N,M=map(int,input().split())
arr=np.array([input().split() for i in range (N)],int)

print('Outut')
print(np.mean(arr,axis=1))
print(np.var(arr,axis=0))
print(np.std(arr,axis=None).round(11))

Input
2 2
1 2 
3 4
Outut
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


## Q.12 Dot and Cross

You are given two arrays A and B. Both have dimensions of N X N.
Your task is to compute their matrix product.

### Input Format
The first line contains the integer N.

The next N lines contains N space separated integers of array A .

The following N lines contains N space separated integers of array B .

### Output Format
Print the matrix multiplication of A and B .

### Sample Input
    2
    1 2
    3 4
    1 2
    3 4

### Sample Output
    [[ 7 10]
    [15 22]

In [11]:
import numpy as np
print('Input')
N=int(input())

A=np.array([input().split() for i in range (N)],int)
B=np.array([input().split() for i in range (N)],int)

print('\nOutput')
print(np.dot(A,B))


Input
2
1 2 
3 4 
1 2 
3 4

Output
[[ 7 10]
 [15 22]]


## Q.13 Inner and Outer

You are given two arrays: A and B .
Your task is to compute their inner and outer product.

### Input Format
The first line contains the space separated elements of array A.

The second line contains the space separated elements of array B.

### Output Format
First, print the inner product.

Second, print the outer product.

### Sample Input
    0 1
    2 3

### Sample Output
    3
    [[0 0]
     [2 3]

In [12]:
import numpy as np

print('Input')
A=np.array([input().split()],int)
B=np.array([input().split()],int)

print('Outut')
print(np.inner(A,B)[0][0])
print(np.outer(A,B))


Input
0 1
2 3
Outut
3
[[0 0]
 [2 3]]


## Q.14 Polynomials

You are given the coefficients of a polynomial P .
Your task is to find the value of P at point x .

### Input Format
The first line contains the space separated value of the coefficients in P.
The second line contains the value of x.

### Output Format
Print the desired value.

### Sample Input
    1.1 2 3
    0

### Sample Output
    3.0

In [2]:
import numpy as np
print('Input')
arr=list(map(float,input().split()))
n=int(input())
print('\nOutput')
print(np.polyval(arr,n))

Input
1.1 2 3
0

Output
3.0


## Q.15 Linear Algebra

You are given a square matrix A with dimensions N X N. Your task is to find the determinant. Note: Round the answer to 2 places after the decimal.

### Input Format

The first line contains the integer N.
The next N lines contains the N space separated elements of array A.

### Output Format

Print the determinant of A .

### Sample Input

    2
    1.1 1.1
    1.1 1.1

### Sample Output

    0.0

In [4]:
import numpy as np
print('Input')
N=int(input())

A=np.array([input().split()for i in range (N)],float)
print('\nOutput')
print(np.linalg.det(A).round(2))



Input
2
1.1 1.1
1.1 1.1

Output
0.0
